//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the parallel_planner package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __parallel_planner__PLANNERCONFIGCONFIG_H__
#define __parallel_planner__PLANNERCONFIGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace parallel_planner
{
  class PlannerConfigConfigStatics;

  class PlannerConfigConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(PlannerConfigConfig &config, const PlannerConfigConfig &max, const PlannerConfigConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PlannerConfigConfig &config1, const PlannerConfigConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PlannerConfigConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PlannerConfigConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PlannerConfigConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PlannerConfigConfig &config) const = 0;
      virtual void getValue(const PlannerConfigConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PlannerConfigConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T PlannerConfigConfig::* field;

      virtual void clamp(PlannerConfigConfig &config, const PlannerConfigConfig &max, const PlannerConfigConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PlannerConfigConfig &config1, const PlannerConfigConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PlannerConfigConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PlannerConfigConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PlannerConfigConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PlannerConfigConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PlannerConfigConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PlannerConfigConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PlannerConfigConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<PlannerConfigConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PlannerConfigConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("kf_update_rate"==(*_i)->name){kf_update_rate = boost::any_cast<double>(val);}
        if("kf_pos_noise"==(*_i)->name){kf_pos_noise = boost::any_cast<double>(val);}
        if("kf_vel_noise"==(*_i)->name){kf_vel_noise = boost::any_cast<double>(val);}
        if("dsm_max_accel"==(*_i)->name){dsm_max_accel = boost::any_cast<double>(val);}
        if("dsm_max_jerk"==(*_i)->name){dsm_max_jerk = boost::any_cast<double>(val);}
        if("vfh_horizontal_res"==(*_i)->name){vfh_horizontal_res = boost::any_cast<int>(val);}
        if("vfh_vertical_res"==(*_i)->name){vfh_vertical_res = boost::any_cast<int>(val);}
        if("vfh_clearance_radius"==(*_i)->name){vfh_clearance_radius = boost::any_cast<double>(val);}
        if("vfh_cost_yaw_weight"==(*_i)->name){vfh_cost_yaw_weight = boost::any_cast<double>(val);}
        if("vfh_cost_goal_weight"==(*_i)->name){vfh_cost_goal_weight = boost::any_cast<double>(val);}
        if("vfh_obstacle_threshold"==(*_i)->name){vfh_obstacle_threshold = boost::any_cast<int>(val);}
        if("sensor_range_max"==(*_i)->name){sensor_range_max = boost::any_cast<double>(val);}
        if("max_forward_speed"==(*_i)->name){max_forward_speed = boost::any_cast<double>(val);}
        if("goal_x"==(*_i)->name){goal_x = boost::any_cast<double>(val);}
        if("goal_y"==(*_i)->name){goal_y = boost::any_cast<double>(val);}
        if("goal_z"==(*_i)->name){goal_z = boost::any_cast<double>(val);}
      }
    }

    double kf_update_rate;
double kf_pos_noise;
double kf_vel_noise;
double dsm_max_accel;
double dsm_max_jerk;
int vfh_horizontal_res;
int vfh_vertical_res;
double vfh_clearance_radius;
double vfh_cost_yaw_weight;
double vfh_cost_goal_weight;
int vfh_obstacle_threshold;
double sensor_range_max;
double max_forward_speed;
double goal_x;
double goal_y;
double goal_z;

    bool state;
    std::string name;

    
}groups;



//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double kf_update_rate;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double kf_pos_noise;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double kf_vel_noise;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double dsm_max_accel;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double dsm_max_jerk;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int vfh_horizontal_res;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int vfh_vertical_res;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double vfh_clearance_radius;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double vfh_cost_yaw_weight;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double vfh_cost_goal_weight;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int vfh_obstacle_threshold;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double sensor_range_max;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_forward_speed;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double goal_x;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double goal_y;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double goal_z;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PlannerConfigConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PlannerConfigConfig &__max__ = __getMax__();
      const PlannerConfigConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PlannerConfigConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PlannerConfigConfig &__getDefault__();
    static const PlannerConfigConfig &__getMax__();
    static const PlannerConfigConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PlannerConfigConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PlannerConfigConfig::ParamDescription<std::string>::clamp(PlannerConfigConfig &config, const PlannerConfigConfig &max, const PlannerConfigConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PlannerConfigConfigStatics
  {
    friend class PlannerConfigConfig;

    PlannerConfigConfigStatics()
    {
PlannerConfigConfig::GroupDescription<PlannerConfigConfig::DEFAULT, PlannerConfigConfig> Default("Default", "", 0, 0, true, &PlannerConfigConfig::groups);
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.kf_update_rate = 1.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.kf_update_rate = 100.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.kf_update_rate = 20.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("kf_update_rate", "double", 0, "Частота обновления фильтра Калмана (Гц)", "", &PlannerConfigConfig::kf_update_rate)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("kf_update_rate", "double", 0, "Частота обновления фильтра Калмана (Гц)", "", &PlannerConfigConfig::kf_update_rate)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.kf_pos_noise = 0.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.kf_pos_noise = 10.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.kf_pos_noise = 0.1;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("kf_pos_noise", "double", 0, "Ковариация шума по положению", "", &PlannerConfigConfig::kf_pos_noise)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("kf_pos_noise", "double", 0, "Ковариация шума по положению", "", &PlannerConfigConfig::kf_pos_noise)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.kf_vel_noise = 0.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.kf_vel_noise = 10.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.kf_vel_noise = 0.05;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("kf_vel_noise", "double", 0, "Ковариация шума по скорости", "", &PlannerConfigConfig::kf_vel_noise)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("kf_vel_noise", "double", 0, "Ковариация шума по скорости", "", &PlannerConfigConfig::kf_vel_noise)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.dsm_max_accel = 0.1;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.dsm_max_accel = 10.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.dsm_max_accel = 2.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("dsm_max_accel", "double", 0, "Максимальное ускорение (м/с^2)", "", &PlannerConfigConfig::dsm_max_accel)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("dsm_max_accel", "double", 0, "Максимальное ускорение (м/с^2)", "", &PlannerConfigConfig::dsm_max_accel)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.dsm_max_jerk = 0.1;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.dsm_max_jerk = 20.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.dsm_max_jerk = 5.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("dsm_max_jerk", "double", 0, "Максимальный рывок (м/с^3)", "", &PlannerConfigConfig::dsm_max_jerk)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("dsm_max_jerk", "double", 0, "Максимальный рывок (м/с^3)", "", &PlannerConfigConfig::dsm_max_jerk)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.vfh_horizontal_res = 1;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.vfh_horizontal_res = 45;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.vfh_horizontal_res = 5;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<int>("vfh_horizontal_res", "int", 0, "Горизонтальная дискретизация (градусы)", "", &PlannerConfigConfig::vfh_horizontal_res)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<int>("vfh_horizontal_res", "int", 0, "Горизонтальная дискретизация (градусы)", "", &PlannerConfigConfig::vfh_horizontal_res)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.vfh_vertical_res = 1;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.vfh_vertical_res = 45;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.vfh_vertical_res = 5;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<int>("vfh_vertical_res", "int", 0, "Вертикальная дискретизация (градусы)", "", &PlannerConfigConfig::vfh_vertical_res)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<int>("vfh_vertical_res", "int", 0, "Вертикальная дискретизация (градусы)", "", &PlannerConfigConfig::vfh_vertical_res)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.vfh_clearance_radius = 0.1;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.vfh_clearance_radius = 5.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.vfh_clearance_radius = 0.8;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("vfh_clearance_radius", "double", 0, "Минимальное безопасное расстояние (м)", "", &PlannerConfigConfig::vfh_clearance_radius)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("vfh_clearance_radius", "double", 0, "Минимальное безопасное расстояние (м)", "", &PlannerConfigConfig::vfh_clearance_radius)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.vfh_cost_yaw_weight = 0.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.vfh_cost_yaw_weight = 10.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.vfh_cost_yaw_weight = 1.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("vfh_cost_yaw_weight", "double", 0, "Вес предпочтения по курсу", "", &PlannerConfigConfig::vfh_cost_yaw_weight)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("vfh_cost_yaw_weight", "double", 0, "Вес предпочтения по курсу", "", &PlannerConfigConfig::vfh_cost_yaw_weight)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.vfh_cost_goal_weight = 0.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.vfh_cost_goal_weight = 10.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.vfh_cost_goal_weight = 3.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("vfh_cost_goal_weight", "double", 0, "Вес предпочтения по направлению к цели", "", &PlannerConfigConfig::vfh_cost_goal_weight)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("vfh_cost_goal_weight", "double", 0, "Вес предпочтения по направлению к цели", "", &PlannerConfigConfig::vfh_cost_goal_weight)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.vfh_obstacle_threshold = 0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.vfh_obstacle_threshold = 100;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.vfh_obstacle_threshold = 5;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<int>("vfh_obstacle_threshold", "int", 0, "Порог засоренности для препятствия", "", &PlannerConfigConfig::vfh_obstacle_threshold)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<int>("vfh_obstacle_threshold", "int", 0, "Порог засоренности для препятствия", "", &PlannerConfigConfig::vfh_obstacle_threshold)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.sensor_range_max = 1.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.sensor_range_max = 50.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.sensor_range_max = 10.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("sensor_range_max", "double", 0, "Максимальная дальность сенсора (м)", "", &PlannerConfigConfig::sensor_range_max)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("sensor_range_max", "double", 0, "Максимальная дальность сенсора (м)", "", &PlannerConfigConfig::sensor_range_max)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_forward_speed = 0.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_forward_speed = 10.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_forward_speed = 2.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("max_forward_speed", "double", 0, "Максимальная поступательная скорость (м/с)", "", &PlannerConfigConfig::max_forward_speed)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("max_forward_speed", "double", 0, "Максимальная поступательная скорость (м/с)", "", &PlannerConfigConfig::max_forward_speed)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.goal_x = -100.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.goal_x = 100.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.goal_x = 15.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("goal_x", "double", 0, "Цель X", "", &PlannerConfigConfig::goal_x)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("goal_x", "double", 0, "Цель X", "", &PlannerConfigConfig::goal_x)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.goal_y = -100.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.goal_y = 100.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.goal_y = 15.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("goal_y", "double", 0, "Цель Y", "", &PlannerConfigConfig::goal_y)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("goal_y", "double", 0, "Цель Y", "", &PlannerConfigConfig::goal_y)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.goal_z = 0.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.goal_z = 20.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.goal_z = 4.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("goal_z", "double", 0, "Цель Z", "", &PlannerConfigConfig::goal_z)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PlannerConfigConfig::AbstractParamDescriptionConstPtr(new PlannerConfigConfig::ParamDescription<double>("goal_z", "double", 0, "Цель Z", "", &PlannerConfigConfig::goal_z)));
//#line 245 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 245 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(PlannerConfigConfig::AbstractGroupDescriptionConstPtr(new PlannerConfigConfig::GroupDescription<PlannerConfigConfig::DEFAULT, PlannerConfigConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<PlannerConfigConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PlannerConfigConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PlannerConfigConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PlannerConfigConfig __max__;
    PlannerConfigConfig __min__;
    PlannerConfigConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PlannerConfigConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PlannerConfigConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PlannerConfigConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PlannerConfigConfig &PlannerConfigConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PlannerConfigConfig &PlannerConfigConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PlannerConfigConfig &PlannerConfigConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PlannerConfigConfig::AbstractParamDescriptionConstPtr> &PlannerConfigConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PlannerConfigConfig::AbstractGroupDescriptionConstPtr> &PlannerConfigConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PlannerConfigConfigStatics *PlannerConfigConfig::__get_statics__()
  {
    const static PlannerConfigConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PlannerConfigConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PLANNERCONFIGRECONFIGURATOR_H__
